### ISSUE TITLE
Invalid detection replacement char  AnyMatcher

### ISSUE THREAD

**Issue by RedSkotina** [mna/pigeon#17]
replacement char incorrectly detected as an encoding error in AnyMatcher.
Peg:  Test <- "[" s:. "]" 
Input: [�]
Expect: Match
Output: 2016/09/08 23:05:22 stdin:1:1 (0): no match found 
Debug trace:

> 1:1:0: parseRule Test [U+005B '[']
> 1:1:0: parseActionExpr [U+005B '[']
> 1:1:0: parseSeqExpr [U+005B '[']
>     > 1:1:0: parseLitMatcher [U+005B '[']
>    < 1:2:1: parseLitMatcher [U+FFFD '?']
>     > 1:2:1: parseLabeledExpr [U+FFFD '?']
>      > 1:2:1: parseAnyMatcher [U+FFFD '?']
>     < 1:2:1: parseAnyMatcher [U+FFFD '?']
>    < 1:2:1: parseLabeledExpr [U+FFFD '?']
>     > 1:2:1: restore [U+FFFD '?']
>    < 1:1:0: restore [U+005B '[']
>   < 1:1:0: parseSeqExpr [U+005B '[']
>  < 1:1:0: parseActionExpr [U+005B '[']
> < 1:1:0: parseRule Test [U+005B '[']

Probably problem with replacement chat also exist in CharClassMatcher, but need tests

**Comment by breml** [comment]
@RedSkotina I think, this was fixed with #42. Do you agree?

**Comment by breml** [comment]
Close as resolved.
