### ISSUE TITLE
ParseFile swallows parse errors

### ISSUE THREAD

**Issue by vito** [mna/pigeon#35]
[This line](https://github.com/mna/pigeon/blob/69502cc142182b8c90270fe2f152d983df11efcb/builder/static_code.go#L94) causes the err return value of `.parse()` below it to be overridden with the result of closing the file.

Not sure what the best fix would be. It could either ignore the result, or only set `err` if it's `nil` to begin with, or return both errors glued together but that seems a bit overkill.

Great project, by the way - it's saved me a ton of time and is very easy to work with!

**Comment by breml** [comment]
@vito Thanks for the bug report, fixed it by only returning the close error, if it is not nil.
