### ISSUE TITLE
Syntax Highlighting in Vim

### ISSUE THREAD

**Issue by jasontbradshaw** [mna/pigeon#38]
I've created a syntax highlighting Vim plugin for `pigeon` grammar files, https://github.com/jasontbradshaw/pigeon.vim:

I thought it might be useful to point others to it, possibly by adding it to the README if anyone finds it interesting and/or useful.

If not, no worries! Just wanted to throw it out there.

Here's a sample of what it looks like in the `jellybeans` color scheme:

![screenshot-2017-08-31t18 37 26z](https://user-images.githubusercontent.com/178706/29949592-805dfa0c-8e7b-11e7-82ee-936b732fa9f1.png)

**Comment by breml** [comment]
@jasontbradshaw Thank you very much for your work and the link. I added it to the [Pigeon Wiki](https://github.com/mna/pigeon/wiki) and updated the README.md to include a reference to the Wiki.

**Comment by jasontbradshaw** [comment]
Thank you! I hope others find it as useful as I have.
