### ISSUE TITLE
Proposal on How to Maintain the State of the Parser in Pigeon

### ISSUE THREAD

**Issue by breml** [mna/pigeon#40]
# Current Situation

## State within the Parser

Originally the state of the parser mainly consisted of the current position of the cursor within the parsed data. Additionally, a list of errors, which occurred during the parsing, is kept by the parser, which could be seen as state as well.

With the addition of the GlobalStore feature (`current.globalStore`), a central place to maintain arbitrary data during parsing was added. For example this could be used to provide the parser with configuration data.

With the current implementation of Pigeon it is not possible to parse inputs, where some kind of state has to be maintained. The most prominent example is: significant white space parsing (e.g. Python source code).

## Go Code Blocks in the Parser

Currently, Pigeon allows to embed Go code in the following ways:

1. **Initializer Code Block**: Go code block, which is copied as-is into the generated parser, required to generate proper Go source files (as a minimum requirement, this code block has to provide the `package` statement).
2. **Action Expression**: contains Go code to control what value is returned as the result of a parsing rule. This code block is turned into a method on the `*current` type.
3. **AndCode Expression** / **NotCodeExpression**: the code predicate are similar to the normal predicate expressions (`&{}` and `!{}`). Rather than performing a look-ahead, they execute Go code to evaluate, if the processing of the current parsing tree should continue or if the parser should backtrack. This code blocks are turned into methods on the `*current` type.

With the existing code blocks it is possible to initialize the parser, specify the result of an expression or a rule and to control the flow of the parser. What currently is missing is, a way to change the state of the parser.

Currently, to workaround this limitation, the AndCodeExpr (`&{}`) is used in the examples for Global State as well as in the PR for the [labeled failures](https://github.com/mna/pigeon/pull/39), which is semantically not the right way to do this.

# Proposal

## State within the Parser

* `current.globalStore` — is a general global store for the user to store arbitrary key, value pairs that they need to manage and that they do not want tied to the backtracking of the parser. This is only modified by the user and _never_ rolled back by the parser. It is always up to the user to keep this in a consistent state.
* `current.state` — is a store for arbitrary key,value pairs that the user wants to be tied to the backtracking of the parser. This is _always_ restored if a parsing rule fails.
* `current.pos`, `current.text` — are variables managed only by the parser and the user is only allowed to read but not update. This is _always_ restored and managed by the parser. The user is not allowed to modify this.
* `parser.errs` (`ErrList`) — list of errors, occurred during parsing. Errors are added by the parser (e.g. "grammar has no rule", "invalid encoding") as well as by the user (e.g. `return true, errors.New(...)` in AndCodeExpression). This is _never_ rolled back by the parser.

## State Change Expression

A new expression type **State Change Expression** (`#{}`) is introduced. The state change expression operates on `*current` and is allowed to change the internal state of the parser. This includes to:

* Change the global store (add, modify and remove values)
* Change the global state (add, modify and remove values)
* Add/raise parsing errors (without resulting the current parsing rule to fail, the same as `&{ return true, errors.New("New error") }` )

With this new expression in place, the modifiable elements of the parser state must no longer be changed by the AndCodeExpressions, NotCodeExpressions and ActionExpression, as the state is considered read-only in those expressions. Therefore those changes are reverted.

# Backtracking / Restore old State / Memoization

If the parser performs a backtracking, the following elements of the state are restored to their old values before an alternative parsing tree is tried:

* Current position of the parser (`current.pos`) and the respective data (`current.text`)
* Global state (`current.state`)

This also has to work, if memoization is used.

# Open Questions

* Should the state change expression be used to add/raise parsing errors?
* Should the ErrList be restored as well, if a backtracking is performed? (The farthestFailure must not be restored, because to keep this information is the whole purpose of this feature).
* What is the best way to return from the parser, if the parsing it self is successful, but still there are errors reported (this is possible with the labeled failures PR, especially if used for robust parsing).

**Comment by RedSkotina** [comment]
About memoization: https://github.com/mna/pigeon/issues/14

**Comment by breml** [comment]
@RedSkotina Thanks for the hint about memoization. As I understand your example in https://github.com/mna/pigeon/pull/15/files#diff-2e565dcb9f8c9aacb131b983e5f5b85dR25, the problem is, that the memoization is not aware of the additional variables (`data` and `idx`), which in a way also belong to the current state of the parser. With the proposed extension of the parser, the global state must be memoized as well (and also taken into consideration, if a memoized result could be used or if the parser has to reevaluate). A memoized result may only be used, if the parser evaluates the same rule with the same global state at the same position (within the parsed data).

With the above proposed extension of pigeon, it would no longer be "valid" to use the AndCodeExpression (`&{}`) in the you used it in https://github.com/mna/pigeon/issues/14.

So in the end it really makes sense to add the state change expression `#{}`.

**Comment by jlozano** [comment]
@breml apologies for the delay in reviewing this! I have a couple of questions:

## State Change Expression
> With this new expression in place, the modifiable elements of the parser state must no longer be changed by the AndCodeExpressions, NotCodeExpressions and ActionExpression, as the state is considered read-only in those expressions. 

How do we enforce this? Do we always revert the state after these expressions, regardless if the parsing rule failed or not? e.g consider the following scenario:
```
start = isA readA
isA = &{if c.text == "a" { c.state["a"] = 0} }
readA = "a" { c.state["a"].(int)++; return nil, nil }
```
and we parse the input `a`.
Would the parser panic (since `c.state["a"]` is only initialized to an int in the `isA` rule)?

## Open questions
> Should the state change expression be used to add/raise parsing errors?

Hmm what would be the benefits of this? As far as I can tell it would be something like:

Benefits:
- Simplify parser conceptually so all state except for `current.pos`, `current.text`, and `current.globalStore` appears in (and is managed by) `current.state`.
- Clients now have access to the error list, can potentially add or remove errors themselves in `#{}` expressions.

Drawbacks:
- To add an error to the error list now requires a map lookup and a cast.
- Clients can now mess up the state of the error list.

I am sure there are other benefits and drawbacks that I am missing.

> Should the ErrList be restored as well, if a backtracking is performed? (The farthestFailure must not be restored, because to keep this information is the whole purpose of this feature).

Hmm good question. Perhaps we should leave the error behavior as is and revisit this in a separate issue after we have more data? 

> What is the best way to return from the parser, if the parsing it self is successful, but still there are errors reported (this is possible with the labeled failures PR, especially if used for robust parsing).

Hmm good question, I was thinking that we stick with what we have now, e.g:
For `Parse` we return the following:
- `nil, &errList{errNoRule}` if `len(g.rules) == 0`
- `nil, p.errs.err()` if parsing fails, e.g `parseRule` fails here: https://github.com/mna/pigeon/blob/master/builder/static_code.go#L583
- `nil, p.errs.err()` if the parser panics, e.g this block https://github.com/mna/pigeon/blob/master/builder/static_code.go#L563
- `val, p.errs.err()` in all other cases.

For `ParseReader` the same as above with the added case
- `nil, err` if there is an error reading the contents of the reader into a buffer.

I think that the client should be in charge of examining the errors and determining if they should still accept the result. I also think that in the case of robust parsing it is helpful to know which errors did occur, and to be able to print these out. 

What do you think?

**Comment by breml** [comment]
@jlozano Thanks for your reply.

# State Change Expression

The short answer is: Yes, we would revert the state after those expressions regardless of the result.
With this proposal implemented, the proper way to formulate the grammar would be:

```
start = isA readA
isA = &{ return c.text == "a", nil } #{ c.state["a"] = 0; return nil }
readA = "a" { c.state["a"].(int)++; return nil, nil }
```
With this, the state change expression only gets executed, if the AndCodeExpression is successful.

# Open Questions

> Should the state change expression be used to add/raise parsing errors?

My was not thinking about adding errors directly to the list (within the parser). My question was if the state change expressions return errors, which get added to the list of errors (the same way it is done in AndCodeExpressions and ActionExpressions. (My opinion is, that this should be the case.)

Additionally I am wondering, if these errors should be removed from the error list, if a backtracking is performed (see also the next question).

> Should the ErrList be restored as well, if a backtracking is performed? (The farthestFailure must not be restored, because to keep this information is the whole purpose of this feature).

I am fine with keeping the current behavior. I was just wondering, if there are situations, where during the parsing an error is added to the error list, then later the parser backtracks and in the next alternative parse branch, the input is parsed without error (but still, the error from the first tried alternative is returned as error). In this case, the problem is, that an err is returned, even though the parsing was successful.

So the main question is, if in a parse branch an error is raised and later this parse branch is backtracked, and an other alternative parse branch is successful, does it make sense to return the errors from the parse branches, which were not successful.

> What is the best way to return from the parser, if the parsing it self is successful, but still there are errors reported (this is possible with the labeled failures PR, especially if used for robust parsing).

I am fine with your thoughts here and in #39. We stick to the current behavior and maybe add [option 3](https://github.com/mna/pigeon/pull/39#issuecomment-330901229) later, if there is really a valid case for it.

**Comment by jlozano** [comment]
@breml 

State change expression -- got it, makes sense.

> My was not thinking about adding errors directly to the list (within the parser). My question was if the state change expressions return errors, which get added to the list of errors (the same way it is done in AndCodeExpressions and ActionExpressions. (My opinion is, that this should be the case.)

Got it, I agree, I think that this makes sense.

> So the main question is, if in a parse branch an error is raised and later this parse branch is backtracked, and an other alternative parse branch is successful, does it make sense to return the errors from the parse branches, which were not successful.

Ahh gotcha, interesting, what do we do for `&{}` and `!{}` expressions?

**Comment by breml** [comment]
The current behavior is, that if `&{}` or `!{}` expressions do return an error (but do not fail the parsing, that is, `&{}` returns `true`), the error is added to the list of errors. If the parser later fails, those errors are not removed from the list. Or with other words, with the current implementation, if an error is added to the list, it stays there regardless of if the parsing is successful, backtracking or failing.

**Comment by breml** [comment]
Initial implementation in #43.
