### ISSUE TITLE
Feature proposal: alternate entrypoints

### ISSUE THREAD

**Issue by mna** [mna/pigeon#44]
Hello,

At the moment, pigeon hard-codes the entrypoint (starting rule) of the generated parsers - the first rule in the grammar serves as the entrypoint. One area where this constraint is particularly painful is for tests: imagine for example that you want to test in isolation a specific area of the grammar (e.g. string literals, numbers, etc.). Currently you're left with a few less-than-ideal solutions:

- generate a fully valid input that includes the rule to test (depending on the grammar, may require non-trivial unnecessary input to be maintained in addition to the input to test, and is not an isolated test)
- split the grammar in various files (e.g. "main" grammar and as many "entrypoint" partial grammar files as necessary, and `$ cat entrypoint_test1.peg main_grammar.peg > complete_grammar.peg` them to generate as many different parsers as necessary). This works at the cost of many additional files and relies heavily on Makefiles.
- hack the internals of pigeon (identify the index of the "rule under test" in `g.rules` and swap it with the rule at index 0) - which doesn't play well with `-optimize-grammar` (the "rule-under-test" may have been optimized out) and is not very flexible (maybe we want to test a combination of existing rules, or make sure that the test matches the full input - that is, a given rule followed by `EOF`).

I'd like to propose a new command-line flag and a new `Parse` option to support alternate entrypoints natively. This implementation supports:

- A single grammar file (no need to split into multiple entrypoints with subsequent concatenation)
- Support for `-optimize-grammar` (the alternate entrypoints are treated the same as the first rule)
- Flexibility of the alternate entrypoints (not limited to other existing rules, can be an otherwise non-referenced rule)
- Opt-in feature (if no alternate entrypoints are specified, works the same as today, with no performance impact)
- Only rules specified when the parser is generated can be used as entrypoints (i.e. non-referenced rules that are not valid alternate entrypoints are still optimized out)

I have a working implementation in branch `wip-testrules`. As you can see among the noise of the generated files, the changes are quite targeted and do not spread all over the codebase, there's the command-line flag, the `Entrypoint` option, the `Optimize` call and the parser picks the right rule at the start of the parsing.

Let me know your thoughts about this and any comments you may have on the current implementation. For example, I chose to call the flag `-alternate-entrypoints` so that the first rule is always implicitly a valid entrypoint. I think that makes the whole API cleaner and has less impact on backwards compatibility (e.g. otherwise if the flag is `entrypoints`, it is special when not set - implies first rule - but when set it would need to include the first rule if desired), but that's just my point of view.

Thanks,
Martin

**Comment by breml** [comment]
@mna I am glad to see you working on pigeon. I really like your proposal and think it is very valuable.

I will give it some more thoughts in the next days and provide a more detailed feedback.

In meantime, do you mind to submit this change as a PR, because it allows to comment directly inside the code. (Maybe you first rebase your code on current master.)

**Comment by mna** [comment]
Hey Lucas, thanks, yeah it's nice to start using it again. You've done a great job with the optimization options by the way. I haven't followed enough the parser state development to give an educated opinion on it though.

I was gonna submit a PR, but I wanted to discuss it first in an issue to gauge interest (and to follow my own guidelines in the contributions file! :) I'll create the PR later today, after rebasing on master.

Thanks,
Martin

**Comment by breml** [comment]
Thanks for the compliment, the optimization of the pigeon parser was a joyful work to do.
I left some minor comments on the PR. In general this already looks very good in my opinion.

**Comment by breml** [comment]
Implemented with #45.
