### ISSUE TITLE
Accessing labels defined in parent expression from subexpressions

### ISSUE THREAD

**Issue by erjoalgo** [mna/pigeon#5]
Hi, 

I'm having trouble acccessing a label defined in the parent expression from a subexpression. 
I read another issue where it is mentioned that:
"...labels are allowed in subexpressions, but they are available to code blocks in those subexpressions only. It's very similar to lexical scoping in programming languages, if that helps. Open a new scope and declare a var, that var is visible within that scope, but not in its parent scope."

So I'm trying to use this scoping intuition as follows:

``` golang
{
    package main
}
A <- 
    ("B" b:B
        ( "C" c:C
            {return b + c, nil}
            /
          "D" d:d
            {return b + d, nil}
        ))
/
    ( "E"  )
{
    return "E", nil
}
B <- "B"{return "B", nil}
C <- "C"{return "C", nil}
```

But the generated "onA..." function doesn't have a 'b' parameter:

``` golang
func (c *current) onA7(c interface{}) (interface{}, error) {
return b + c, nil
}
```

Is there a way to access the value of b from this subexpression?

**Comment by PuerkitoBio** [comment]
That's because the choice operator "/" starts a new scope - only one of the choices can match, so you should have code for each choice (e.g. Before the /, you'd see the "d").

**Comment by erjoalgo** [comment]
Shouldn't the code in the first two blocks have access to 'b'?
The first block, which does this:
```
return b + c, nil
```

doesn't have access to the 'b' label:

```
func (c *current) onA7(c interface{}) (interface{}, error) {
return b + c, nil
}
```

**Comment by breml** [comment]
This is by design, the right way to do this would be like this:

```
{
    package main
}
A <- 
    ("B" b:B
        cd:( "C" c:C
            {return c, nil}
            /
          "D" d:d
            {return d, nil}
        ) { return b + cd, nil }
    )
/
    ( "E"  )
{
    return "E", nil
}
B <- "B"{return "B", nil}
C <- "C"{return "C", nil}
```

The above code is "pseudo" code and would not work directly, because all values are `interface{}` and it is therefore not possible to add them directly.
