### ISSUE TITLE
Backtrack-aware state does not restore correctly

### ISSUE THREAD

**Issue by mna** [mna/pigeon#51]
Hello, 

As I understand it, the backtrack-aware state store (`current.state`) should follow the parser's backtracking and by the end of the parsing, it should only hold the data written in state code blocks of valid matches (`#{ ... }`).

However, currently pigeon will only restore the state in a handful of cases:
* After an Action code block
* After an And or Not predicate code block
* After a Choice expression that did not match

The first two seem correct, as the state store is read-only in all code blocks but the state-specific one. However, the third is insufficient to rollback the state in all cases where the parser backtracks.

A minimal example of how it can fail is provided in https://github.com/mna/pigeonstatebug (you can just run make and it will run with the sample input `"f#\n"` and should count 8 newlines).

This is because the parser can backtrack in any kind of rule, e.g. given that rule:

```
// match any whitespace followed by a 'Z'
_ <- [ \t\n]*
Z_ <- _ 'Z'
```

With this input: " A", the `_` rule will match, but not the 'Z', so the parser will backtrack but not the state (because this is a sequence expression).

I'm working on it today and will try to provide a pull request. I think the state should clone and restore everywhere where the parser saves and restores the position (so that it truly follows the backtracking of the parser - in addition to restoring after the non-state code blocks of course).

Thanks,
Martin

**Comment by breml** [comment]
@mna Thanks for your bug report and the PR.

I agree, there is a problem with the current implementation of the backtracking of the state store, which is clearly demonstrated by your example code in https://github.com/mna/pigeonstatebug.

Find my detailed comments in the PR.
