### ISSUE TITLE
Significant Whitespace Parsing

### ISSUE THREAD

**Issue by ghost** [mna/pigeon#7]
Good day, @PuerkitoBio.

Are there any plans to implement either parametrisable rules [[1](https://github.com/pegjs/pegjs/issues/45)] or a global state [[2](https://github.com/otac0n/Pegasus/wiki/Significant-Whitespace-Parsing)] [[3](https://github.com/pegjs/pegjs/issues/217)] [[4](https://github.com/pointlander/peg/issues/9)]?

**Comment by PuerkitoBio** [comment]
Hello anonx,

The global state feature seems very interesting, given how useful it is to parse indentation-based languages, thanks for bringing it up. I don't plan to implement this anytime soon - it doesn't look like a quick hack and I'm quite busy with other stuff - but that would definitely make sense. No promises on a date :)

Martin

**Comment by anonx** [comment]
Great anyway. I will look forward to it. Thank you for your work on this project.
