### ISSUE TITLE
UTF-8 replacement character blocks code generation and runtime

### ISSUE THREAD

**Issue by dimus** [mna/pigeon#76]
I am parsing biological scientific names detected in Biodiversity Heritage Library. Due to OCR errors quite many of them contain 'bad' characters that had been replaced by '�', so I need to add the character to a parsing rule.

However when I try to generate the Go code with ``pigeon``, the process stalls indefinitely. If I try to add the '�' to the rule in already generated code, the runtime execution in turn gets stalled indefinitely. Setting ``AllowInvalidUTF8(bool)`` option does not make a difference. The rule in question looked like this:

```
NameLowerChar <- LowerChar / LowerCharExtended / MiscodedChar

MiscodedChar <- '�' {
  addWarn(c, OCRErrorWarn)
  return c.text, nil
}

LowerCharExtended <- [æœſàâåãäáçčéèíìïňññóòôøõöúùüŕřŗššşž] {
  addWarn(c, badCharsWarn)
  return c.text, nil
}

LowerChar <- [a-zë] {
  return c.text, nil
}
```

**Comment by breml** [comment]
@dimus sorry for my slow response. have you tried to escape the U+FFFD char with '\xff' '\xfd'. See also https://github.com/mna/pigeon/blob/master/test/runeerror/runeerror_test.go

**Comment by dimus** [comment]
@breml I guess your approach would work, thank you for your reply. In my case I found that pigeon, being more convenient, and easier to understand/use for a beginner Go programmer like me, did not provide enough parsing speed for my case. So I decided to move my [project](https://gitlab.com/gogna/gnparser) to [peg](https://github.com/pointlander/peg).
