### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by mkeeler** [mna/pigeon#82]
Update: Looks like my problem was just running `go get -u github.com/mna/pigeon`. That brings up another request which is to cut a new release of pigeon so that users can pin to a specific version instead of master.

The peg file in test/thrownrecover does not appear to be valid. I was trying to implement similar error handling and it was failing. I then tried to run `pigeon thrownrecover.peg` within that directory and I get the following error:

```
parse error(s):
 thrownrecover.peg:1:1 (0): no match found
```

**Comment by mkeeler** [comment]
Actually I think its just that I was using 1.0.0. Didn't realize it was 101 commits behind master.

**Comment by breml** [comment]
Thanks for the update. I will think about it. I first have to check if there have been some (significant) breaking changes or if I can go for v1.1.0.

**Comment by ribasushi** [comment]
Ran into this very same problem trying to compile https://github.com/mna/pigeon/blob/master/examples/indentation/indentation.peg

**Comment by flowchartsman** [comment]
Running into this myself. Anyone running into this issue is encouraged to `go get github.com/mna/pigeon@18953b2` (or whatever the latest commit is) from inside of their module until a new release is cut.

**Comment by flowchartsman** [comment]
v1.1.0 would be really great right now. I keep forgetting about this before I remember to check out from head, and if the examples don't build, we're in a bit of an inconsistent state.

**Comment by yfwz100** [comment]
Is there any updates?

**Comment by flowchartsman** [comment]
For those following along, it looks as if we have a [new release now!](https://github.com/mna/pigeon/releases/tag/v1.1.0)
