### ISSUE TITLE
How to achieve quantity {n} in regular expression?

### ISSUE THREAD

**Issue by Jay54520** [mna/pigeon#85]
I found that there are only `? * +` in `grammar/pigeon.peg.SuffixedExpr`, how to achieve quantity {n}?

Now I use `?` to achieve, is there a better way? Such as using `\d\d\d\d?\d?`to achieve `\d{3,5}`.

The exact count: {5}
`\d{5} denotes exactly 5 digits, the same as \d\d\d\d\d.`

The example below looks for a 5-digit number:

`alert( "I'm 12345 years old".match(/\d{5}/) ); //  "12345"`
We can add \b to exclude longer numbers: \b\d{5}\b.

The range: {3,5}, match 3-5 times
To find numbers from 3 to 5 digits we can put the limits into curly braces: \d{3,5}

` alert( "I'm not 12, but 1234 years old".match(/\d{3,5}/) ); // "1234"`
We can omit the upper limit.

Then a regexp \d{3,} looks for sequences of digits of length 3 or more:

`alert( "I'm not 12, but 345678 years old".match(/\d{3,}/) ); // "345678"`
Let’s return to the string +7(903)-123-45-67.

A number is a sequence of one or more digits in a row. So the regexp is \d{1,}:
```
 let str = "+7(903)-123-45-67";

let numbers = str.match(/\d{1,}/g);

alert(numbers); // 7,903,123,45,67
```
From https://javascript.info/regexp-quantifiers

**Comment by breml** [comment]
@Jay54520 The short answer is: No, there is currently no support for quantity the way it is supported e.g. in regular expressions of Javascript or also Go.

Such quantifiers (`{from, until}`) are not part of the specification of PEG. Maybe there is a way to mimic this behavior with `&{ ... }` blocks, but I am not sure about this nor did I try.

**Comment by breml** [comment]
See https://godoc.org/github.com/mna/pigeon#hdr-Code_block for an example how to cound occurances.
