### ISSUE TITLE
Unicode character class match

### ISSUE THREAD

**Issue by rafaeljusto** [mna/pigeon#87]
Hi, I'm probably doing something wrong, but couldn't find any reference in the docs. I've added a rule to match any [Unicode character class](https://golang.org/pkg/regexp/syntax/), digits or hyphens:

```
Term ← _ [\p{L}\d_-]+ _ {
  println(string(c.text))
}
```

But when running `pigeon -o example.peg.go example.peg` I got the error:

```
rule CharClassEscape: invalid escape character
```

If I try to escape the regex (adding an extra slash) it does compile, but the resulted file doesn't generate the expected match for Unicode characters. And as I don't need to escape `\n` it shouldn't be an issue I think.

Any ideas on what I'm doing wrong? 😄

**Comment by breml** [comment]
I am not at my computer right now, so I can not test, but have you tried just `[\pL\d_-]+`?

**Comment by rafaeljusto** [comment]
Thanks for the fast response! I just tried `[\pL\d_-]+` and it also gives the same error message:
```
rule CharClassEscape: invalid escape character
```

I will try to dig into the `pigeon.peg` to figure out where is the issue. 👍

**Comment by mna** [comment]
Hey! Character classes are not regular expressions, so ˋ\d` is not a valid
escape. You can use 0-9 or `\pN` depending on what you want to allow.

Hope this helps,
Martin

**Comment by rafaeljusto** [comment]
@mna That solved the issue! I suspected of the `\p{L}`, and never thought that the issue could be the `\d`. Nice one! Thanks a million 😄
