### ISSUE TITLE
Export parserError and errList 

### ISSUE THREAD

**Issue by breml** [mna/pigeon#9]
I have a package with the parser generated by pigeon and in several separate (main) packages the tools, using the generated parser.

My problem now is, `parserError` and `errList` are not exported, which prevents me from using the suggested (https://godoc.org/github.com/PuerkitoBio/pigeon#hdr-Error_reporting) error handling code in my main packages.

In https://godoc.org/github.com/PuerkitoBio/pigeon#hdr-API_stability the returned error types are  defined, which prevents to change these types (and their fields) to be exported.

What do you suggest in this case? Are there other solutions?

**Comment by PuerkitoBio** [comment]
Hello Lucas,

The `parserError` and `errList` types are generated in the same package as the parser, so they don't have to be exported to be used within the PEG code blocks. Can you give a short example of the problem you run into?

Thanks,
Martin

**Comment by breml** [comment]
Hallo Martin

Thanks for your rapid response.

I am currently writing a some tools (currently a syntax-checker and a "context aware" diff tool) which both use the same parser which is build with pigeon. The configuration files are sometimes modified by hand, which may be error prone. Therefor I try to improve the error messages to support the user as good as possible. I use some of the recommendations from this paper:

* Error Reporting in Parsing Expression Grammars: http://arxiv.org/pdf/1405.6646.pdf

In my current project I have the following structure:

```
.
├── cmd
│   ├── diff
│   │   └── main.go
│   └── parser
│       └── main.go
├── config_parser.go
├── config_parser.peg
└── <some more .go files
```

As you can see, I want to use the package, which contains the generated parser in several, external packages (`main` packages).

In the `main` packages some flags are parsed and after this the parsing is initiated by calling `<packagename>.ParseReader()`.
The returned `error` is of type `errList`, containing zero to many `parserError`. Both these types are not exported and therefore I don't have any possibility to access the internal fields (Inner, pos, usw.).

These informations would help me to provide better error messages and thous help the user finding errors in the configuration files (for example some context/surrounding lines of the parsed file, where the parsing error occured).

Regards,
Lucas

**Comment by PuerkitoBio** [comment]
Thanks for the details, I understand your use-case. I'll take a closer look in the next few days.

**Comment by breml** [comment]
@joshsharp in https://github.com/mna/pigeon/commit/2e7a3c8ae1181b4bd9dc1d4fb8433189758493b8 I implemented an example for exported errors (access parser errors from a different package) as well as a simple implementation for caret style error messages. All of this can be done within the users code and does not need any (breaking) changes to the existing pigeon API.

**Comment by joshsharp** [comment]
Lovely, thanks very much.
