### ISSUE TITLE
Proposed optimization for parseLitMatcher

### ISSUE THREAD

**Issue by philandstuff** [mna/pigeon#94]
Hi there,

I use pigeon for philandstuff/dhall-golang and I started doing some profiling since I noticed that some expressions were quite slow to parse.

After running a profiler, I noticed that a lot of time was being spent in `parseLitMatcher`, and in particular in `strconv.AppendQuote`.  I manually hacked my generated parser to cache the AppendQuote result on the litMatcher struct:

```
type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want_      string // added here
}

// ...

func (lit *litMatcher) want() string {
	if lit.want_ != "" {
		return lit.want_
	}
	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	lit.want_ = val
	return val
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want())
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want())
	return p.sliceFrom(start), true
}
```

This cut my test case runtime by nearly a third, from 5.99s to 4.18s, and specifically cut my parseLitMatcher runtime from 2.43s to 0.09s.

Would you accept a PR with this optimization?  I'm not sure how easily it will generalize so I'm happy to hear critical feedback.

**Comment by breml** [comment]
@philandstuff Thanks for your analysis and the PR. I will have a look at this.
