### ISSUE TITLE
Wish error output format were recognized by emacs compilation-mode & next-error

### ISSUE THREAD

**Issue by kpixley** [mna/pigeon#98]
Some seem to be but others aren't.  I haven't figured out the pattern nor how to fix it.

These are the errors from the generated parser, btw.

**Comment by breml** [comment]
@kpixley can you please provide some more details what exactly you are expecting as well as the errors you get from the generated parser. Otherwise I will not be able to support you on this.

**Comment by kpixley** [comment]
It appears as though there are two factors involved here.

Emacs should parse the error lines as they are but a current Emacs bug prevents this.  It recognizes the error only when the column is a single digit.  I believe this has been reported but it's anyone's guess when a fix would be incorporated of released.

If the column is followed by a colon then a different emacs rule is used and the error is recognized even with multiple digit columns.  I'm currently trying out a 1 character pigeon change, adding the colon, and that has been working for me so far.

More discussion here... https://emacs.stackexchange.com/questions/59804/compilation-mode-and-next-error-confusion

**Comment by breml** [comment]
To me, this does not sound like a problem in pigeon, so I am in favor of closing this issue as won't fix. Please report back, if you do not agree. Otherwise I will close this issue.

**Comment by kpixley** [comment]
Reasonable, although there's a one character fix that works around the emacs bug.

I can post process my parsers for now.  It's a simple change.

It is a pigeon bug in the sense that it is not playing well with others and easily could.  But it's not worth any more time discussing.  Close if you prefer.

**Comment by breml** [comment]
The thing about this one character change is, that it potentially breaks other peoples code, so I do not feel comfortable with changing this.
